src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Phone_Number__c</fullName>
        <label>Bank Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <label>Donation Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <label>Exam Fees Submitted?</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fees_Submitted__c</fullName>
        <label>Fees Submitted</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <label>HomePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Donation__c</fullName>
        <label>Is Donation?</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone  Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll_Number</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_2nd__c</fullName>
        <label>Subjects in which Back(2nd)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_3rd__c</fullName>
        <label>Subjects in which Back(3rd)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_4th__c</fullName>
        <label>Subjects in which Back(4th)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back__c</fullName>
        <label>Subjects in which Back</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X1_st_Sem_Percentage__c</fullName>
        <label>1 st Sem Percentage</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Back__c</fullName>
        <label>1st Sem Back?</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Back__c</fullName>
        <label>2nd Sem Back?</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Percentage__c</fullName>
        <label>2nd Sem Percentage</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rdSem_Percentage__c</fullName>
        <label>3rdSem Percentage</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Back__c</fullName>
        <label>3rd Sem Back?</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Back__c</fullName>
        <label>4th Sem Back?</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Percentage__c</fullName>
        <label>4th Sem Percentage</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Insert_Student_Details.cls
public class Insert_Student_Details {
     public Insert_Student_Details(){
        //Student Information
	Student__c student = new Student__c();
	student.Name = 'Ajay Das';
	student.Roll_Number__c = 2000;
        student.Email__c = 'mkar1@gmail.com';
        student.Mobile_Number__c = '+918016765279';
        student.Father_Name__c = 'Bheem Das';
        student.Father_Mobile_Number__c = '+918016782279';
        student.HomePhone__c = '+918016582279';
        student.Address__c = 'City-Kolkata,Zip-789654,state-WestBengal';
        student.Overall_Grade__c = 'A+';
        //Class Info
        student.Stream__c= 'BCA';
        student.Class__c= 'BCA';
        student.Section__c= 'A';
        //Fees Details
        student.Current_Year__c= 2022;
        student.Fees_Submitted__c ='Yes';
        student.Pending_Fees_Amount__c =0 ;
        student.Exam_Fees_Submitted__c = 'Yes';
        student.Pending_Exam_Fees__c = 0;
        student.Is_Donation__c = 'No';
        student.Donation_Amount__c = 0;
        //Semester Details
        student.X1_st_Sem_Percentage__c	= 70;
        student.X1st_Sem_Back__c= 'No';
        student.Subjects_in_which_Back__c='N/A';
        student.X2nd_Sem_Percentage__c=75;
        student.X2nd_Sem_Back__c='No';
        student.Subjects_in_which_Back_2nd__c='N/A';
        student.X3rdSem_Percentage__c= 76;
        student.X3rd_Sem_Back__c='No';
        student.Subjects_in_which_Back_3rd__c='N/A';
        student.X4th_Sem_Percentage__c=77;
        student.X4th_Sem_Back__c='No';
        student.Subjects_in_which_Back_4th__c='N/A';    
        //Bank Details
	student.Bank_Name__c = 'SBI';
        student.IFSC_Code__c = 'SBINFC1001';
        student.Account_Number__c ='256398451269';
        student.Phone_Number__c ='+916523879642';
        student.Bank_Phone_Number__c='+915825456512';
        student.City__c='Kolkata';
        student.State__c='WestBengal';
	insert student;
        System.Debug('Inserted Record id :'+student);
	}
}